name: mvn build and test, docker build (latest) and push

on: 
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  REGISTRY: ghcr.io
  GITHUB_NAME:  gemeinschaftswerknachhaltigkeit
  IMAGE_NAME: gw-landingpage

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: set up node js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: npm install, build
        run: |
          npm install
          npm run build
          
      - name: build the Docker image
        run: docker build . --file Dockerfile --tag ${{env.REGISTRY}}/${{ env.GITHUB_NAME }}/${{env.IMAGE_NAME}}
        
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: push image (latest) to GitHub Container Registry
        run: docker push ${{env.REGISTRY}}/${{ env.GITHUB_NAME }}/${{env.IMAGE_NAME}}:latest

